name: Jira Add Comment
description: Add a comment to an issue
branding:
  icon: 'align-left'
  color: 'blue'
inputs:
  issues:
    description: Keys of the issues to be commented on
    required: true    
  comment:
    description: Comment
    required: true
runs:
  using: 'node16'
  main: './dist/index.js'
